### ISSUE TITLE
UPL dropdown is empty. How come?

### ISSUE THREAD

**Issue by sgort** [OpenWebconcept/plugin-pdc-base#12]
Installed PDC / Wordpress for development purpose on localhost as described [here](https://github.com/OpenWebconcept/plugin-pdc-base/blob/master/README.md) and supported via #7 

Now I try to add a new pdc item with Inzage strafblad as an example ([UPL link](https://standaarden.overheid.nl/owms/terms/strafbladInz))

Why is it that the UPL dropdown is (still) empty? Is there anything missing in the installation instructions that I didn't follow?

![image](https://user-images.githubusercontent.com/25812095/211308530-80039f4e-dc5e-4171-9257-39f22f45b1c5.png)

Here's the draft item.

![image](https://user-images.githubusercontent.com/25812095/211309382-5d299d48-76d3-4c41-970e-c05a6a434119.png)

**Comment by sanderdekroon** [comment]
You need to fill in the UPL URL in the PDC settings:

![Scherm­afbeelding 2023-01-09 om 14 04 48](https://user-images.githubusercontent.com/1830845/211314634-81cede07-5373-4e31-80b0-ea5965cdc571.png)

**Comment by sgort** [comment]
I'm sorry, but I can't find PDC settings anywhere? I'm almost embarrassed to ask...

![image](https://user-images.githubusercontent.com/25812095/211347964-b1a6e32c-5462-41b7-a3da-c308c45729f8.png)

**Comment by sanderdekroon** [comment]
No worries, because it's suppose to be there! I'm not completely sure, but I thought the Metabox plugin handles adding the settings page. 

Maybe someone from @OpenWebconcept/yard-digital-agency can sort this out. I'm starting to suspect that this plugin might require the paid version of Metabox.

**Comment by niekh1234** [comment]
I think the plugin requires MB settings page to be installed

**Comment by sgort** [comment]
If that's true, then unfortunately the experimentation ends here...

![image](https://user-images.githubusercontent.com/25812095/211384125-f6159251-eb26-4717-a4c9-1ed4ab31694a.png)

**Comment by sanderdekroon** [comment]
The same has been mentioned in a discussion here: [https://github.com/orgs/OpenWebconcept/discussions/15](https://github.com/orgs/OpenWebconcept/discussions/15). 

There are free, open source alternatives like [CMB2](https://github.com/CMB2/CMB2) which look to have the same functionality. If Yard is also willing, we could look into replacing Metabox with an alternative.

**Comment by sgort** [comment]
Thx. Much appreciated.

I consider Holger Peters a PO for this product. I'll contact him. See that the discussion that @rubenvdlinde started is also from before the summer of last year...

**Comment by sgort** [comment]
Fixed it @ Field Lab Maurik today.
