### ISSUE TITLE
Related & expanded items

### ISSUE THREAD

**Issue by sanderdekroon** [OpenWebconcept/plugin-pdc-base#4]
At Súdwest-Fryslân we've created some custom functionality for the PDC Base plugin. I'm wondering of other people might be interested in the same functionality and if so, might it be interesting to merge it into the main plugin.

## Related OpenPUB items
We've been adding related OpenPUB items to the PDC themes response. So when requesting a PDC theme we also query OpenPUB items linked to OpenPUB themes with the same name. We're using this to display related news items when viewing a theme page.

This does require the PDC and OpenPUB plugin to be installed on the same WordPress site.

**Request**
```bash
GET https://your-pdc-url.com/wp-json/owc/pdc/v1/themas/pdc-theme-name
```

**Response**
```json
{
    // Other theme fields...
    "related-openpub": [
        {
            "id": 1337,
            "title": "My awesome news item",
            "slug": "my-awesome-news-item",
            "excerpt": "",
            "date": "2022-12-12 12:12:12",
            "post_status": "publish",
            "image": {
                // Image fields, truncated for clarity
            }
        },
        // More items if found
        {
            // Truncated for clarity
        }
    ]
}
```

## Subthemes
The other is adding (expanding) subthemes linked to a PDC theme. 

**Request**
```bash
GET https://your-pdc-url.com/wp-json/owc/pdc/v1/themas/pdc-theme-name
```

**Response**
```json
{
    // Other theme fields...
    "subthemes": [
        {
            "id": 12345,
            "title": "Subtheme Title",
            "slug": "subtheme-slug",
            "excerpt": "",
            "date": "2022-06-30 15:45:50"
        },
        {
            "id": 56789,
            "title": "Subtheme Title 2",
            "slug": "subtheme-slug-2",
            "excerpt": "",
            "date": "2022-06-30 15:45:00"
        }
    ]
}
```

Are these functionality interesting to add to the base plugin? If so, I will create a PR containing the changes.

**Comment by SimonvanWijhe** [comment]
Hi @sanderdekroon,

I came across this old thread with no responses, so I thought I’d chime in.

At Yard, we’ve never had a request to add related news to PDC themes. It’s an interesting idea, but for now, I don’t think it needs to be included in the pdc-base.

Regarding subthemes, they’re already available on the theme endpoint, so this point is likely outdated.

**Comment by sanderdekroon** [comment]
Dit issue kan inderdaad dicht :) We hebben dit toendertijd opgelost in een eigen plugin.
