### ISSUE TITLE
Installatie PDC in wordpress op localhost

### ISSUE THREAD

**Issue by sgort** [OpenWebconcept/plugin-pdc-base#7]
LS,

Heb Wordpress op Ubuntu localhost via [deze instructie](https://ubuntu.com/tutorials/install-and-configure-wordpress#1-overview).

Volg daarna de instructie voor plugin pdc alhier en kom tot punt 2 https://github.com/OpenWebconcept/plugin-pdc-base/blob/b4d2f6fcde1481a6d241ecf42c7496a9352ce30c/README.md?plain=1#L16

Dan verschijnt in mijn dashboard de volgende fout (met een idd nog niet actief plugin onderin...). Voordat ik zelf ga zitten puzzelen. Wat te doen nu? En wil ik dat dan via PR aan de README.md toevoegen wanneer gelukt?

![image](https://user-images.githubusercontent.com/25812095/209140623-68e09f63-c961-483a-aaf6-8a42da2e27aa.png)

**Comment by sanderdekroon** [comment]
Je moet de aangegeven plugins installeren. 

RWMB Metabox: https://wordpress.org/plugins/meta-box/
Posts 2 Posts: https://wordpress.org/plugins/posts-to-posts/

Daarnaast moet je extra dependencies nog installeren met [Composer](https://getcomposer.org/). Afhankelijk van je setup doe je dit door je terminal te openen, naar de OpenPDC plugin map te navigeren en daar `composer install` draaien.

Als je gebruik maakt van bijv. [Bedrock](https://roots.io/bedrock/) kun je je dependencies ook op projectniveau installeren.

**Comment by sgort** [comment]
Getting there. Na install beide plugins is dit de `composer install` output.

![image](https://user-images.githubusercontent.com/25812095/209155700-7f93f494-e7b5-43fc-ac9a-6a931c40762f.png)

**Comment by sanderdekroon** [comment]
Dat klinkt als een permissions issue. Zo te zien kan composer de map niet aanmaken, omdat het onvoldoende rechten heeft. 

Als ik de instructie bekijk waarmee je Wordpress op Ubuntu localhost hebt gezet, gok ik dat de mappen in `www` toegeëigend zijn door een andere user dan de user waarmee je `composer install` uitvoert. 

Los van dit alles: ik zou niet op zo'n manier een development omgeving opzetten. Ik zou je aanraden om eens naar [Docker](https://www.docker.com/) te kijken en dan een algemene LAMP development stack daar op draaien. Zelf doe ik dit met [Devilbox](https://devilbox.readthedocs.io/en/latest/). Je hebt dan geen (of in ieder geval minder) gedoe met permissies en je brengt ook een scheiding aan tussen je machine en je development omgeving.

**Comment by sgort** [comment]
Thx. Will have a look. Docker is welbekend en gebruik ik veel. Devilbox nog onbekend.
