### ISSUE TITLE
(nog) geen rechten om een branch te pushen tbv PR

### ISSUE THREAD

**Issue by sgort** [OpenWebconcept/plugin-pdc-base#8]
Heb branch `7-install-doc` local klaar staan voor suggestie uitbreiding README.md, maar mag geen branch pushen.
```
#steven@steven-Surface-Laptop-3 ~/Development/plugin-pdc-base (7-install-doc) $ git push origin 7-install-doc 
ERROR: Permission to OpenWebconcept/plugin-pdc-base.git denied to sgort.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
steven@steven-Surface-Laptop-3 ~/Development/plugin-pdc-base (7-install-doc) $ 
```

**Comment by sanderdekroon** [comment]
Om wijzigingen door te voeren moet je de repository forken naar je eigen account. Daar commit je de wijzigingen en dan maak je een pull request aan om het te mergen :)

Bekijk ook de [contributing guidelines](https://github.com/OpenWebconcept/.github/blob/5370dd445e25b8bd8063fdae63b33fb41748ef0b/CONTRIBUTING.md).

**Comment by sgort** [comment]
Oh ships. Hahaha. Ik ben al zo lang met regels.overheid.nl op mijn localhost aan de slag dat ik helemaal vergeten ben dat dit idd de route is voor niet-eigen repo's. Sorry hoor. My bad.
